import UserIcon from './components/icons/User';
import EmailIcon from './components/icons/Email';
import PhoneIcon from './components/icons/Phone';
import CompanyIcon from './components/icons/Company';
import DevelopmentIcon from './components/icons/Development';
import DesignIcon from './components/icons/Design';
import MarketingIcon from './components/icons/Marketing';
import OtherIcon from './components/icons/Other';

const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
const phoneRegex = /^\(?(\d{3})\)?[- ]?(\d{3})[- ]?(\d{4})$/;

export const STEP_DETAILS = [
   {
      title: 'Contact details',
      desc: 'Please fill your information so we can get in touch with you.',
      formElements: [
         {
            id: 'contact-f1',
            name: 'name',
            label: 'Name',
            inputType: 'text',
            placeholder: 'John Carter',
            inputIcon: UserIcon,
            isRequired: true,
            errorMessage: 'Name is Required!',
            groupType: 'withLabel',
         },
         {
            id: 'contact-f2',
            name: 'email',
            label: 'Email',
            inputType: 'email',
            placeholder: 'Email address',
            inputIcon: EmailIcon,
            isRequired: true,
            errorMessage: 'Please enter a valid email!',
            groupType: 'withLabel',
            validationCriteria: { pattern: emailRegex },
         },
         {
            id: 'contact-f3',
            name: 'phoneNumber',
            label: 'Phone Number',
            inputType: 'tel',
            placeholder: '(123) 456 - 7890',
            inputIcon: PhoneIcon,
            isRequired: true,
            errorMessage: 'Please enter a valid phone number eg. (123) 456 - 7890!',
            groupType: 'withLabel',
            validationCriteria: { minLength: 10, pattern: phoneRegex },
         },
         {
            id: 'contact-f4',
            name: 'company',
            label: 'Company',
            inputType: 'text',
            placeholder: 'Company name',
            inputIcon: CompanyIcon,
            isRequired: true,
            errorMessage: 'Company is Required!',
            groupType: 'withLabel',
         },
      ],
   },
   {
      title: 'Our services',
      desc: 'Please select which service you are interested in.',
      groupValidation: true,
      groupName: 'service',
      groupErrorMessage: 'Please select a service!',
      formElements: [
         {
            id: 'service-f1',
            name: 'service',
            label: 'Development',
            inputType: 'radio',
            inputIcon: DevelopmentIcon,
            groupType: 'radio',
            isRequired: true,
         },
         {
            id: 'service-f2',
            name: 'service',
            label: 'Web Design',
            inputType: 'radio',
            inputIcon: DesignIcon,
            groupType: 'radio',
            isRequired: true,
         },
         {
            id: 'service-f3',
            name: 'service',
            label: 'Marketing',
            inputType: 'radio',
            inputIcon: MarketingIcon,
            groupType: 'radio',
            isRequired: true,
         },
         {
            id: 'service-f4',
            name: 'service',
            label: 'Other',
            inputType: 'radio',
            inputIcon: OtherIcon,
            groupType: 'radio',
            isRequired: true,
         },
      ],
   },
   {
      title: "What's your project budget?",
      desc: 'Please select the project budget range you have in mind.',
      groupValidation: true,
      groupName: 'budget',
      groupErrorMessage: 'Please select a service!',
      formElements: [
         {
            id: 'budget-f1',
            name: 'budget',
            label: '$5.000 - $10.000',
            inputType: 'radio',
            groupType: 'radio',
            isRequired: true,
         },
         {
            id: 'budget-f2',
            name: 'budget',
            label: '$10.000 - $20.000',
            inputType: 'radio',
            groupType: 'radio',
            isRequired: true,
         },
         {
            id: 'budget-f3',
            name: 'budget',
            label: '$20.000 - $50.000',
            inputType: 'radio',
            groupType: 'radio',
            isRequired: true,
         },
         {
            id: 'budget-f4',
            name: 'budget',
            label: '$50.000 +',
            inputType: 'radio',
            groupType: 'radio',
            isRequired: true,
         },
      ],
   },
];

export const TOTAL_STEPS = STEP_DETAILS.length + 1;

export const TITLE_ENUM = {
   name: 'Name',
   email: 'Email',
   phoneNumber: 'Phone Number',
   company: 'Company Name',
   service: 'Service',
   budget: 'Budget',
};

export const DUMMY_LIST = [
   {
      name: 'Alice Johnson',
      email: 'alice@gmail.com',
      phoneNumber: '9876543210',
      company: 'XYZ Corporation',
      service: 'Mobile App Development',
      budget: '$5,000 - $10,000',
   },
   {
      name: 'Bob Smith',
      email: 'bob@yahoo.com',
      phoneNumber: '8765432109',
      company: 'Tech Innovators',
      service: 'Graphic Design',
      budget: '$15,000 - $25,000',
   },
   {
      name: 'Charlie Brown',
      email: 'charlie@hotmail.com',
      phoneNumber: '7654321098',
      company: 'Digital Solutions',
      service: 'SEO Optimization',
      budget: '$8,000 - $12,000',
   },
   {
      name: 'David Miller',
      email: 'david@outlook.com',
      phoneNumber: '6543210987',
      company: 'Innovate Tech',
      service: 'Content Writing',
      budget: '$12,000 - $18,000',
   },
   {
      name: 'Eva Williams',
      email: 'eva@mail.com',
      phoneNumber: '5432109876',
      company: 'Global Ventures',
      service: 'E-commerce Development',
      budget: '$20,000 - $30,000',
   },
   {
      name: 'Frank Davis',
      email: 'frank@gmail.com',
      phoneNumber: '4321098765',
      company: 'Creative Minds',
      service: 'UI/UX Design',
      budget: '$25,000 - $35,000',
   },
   {
      name: 'Grace Wilson',
      email: 'grace@yahoo.com',
      phoneNumber: '3210987654',
      company: 'Tech Solutions Ltd.',
      service: 'App Testing',
      budget: '$7,000 - $15,000',
   },
   {
      name: 'Henry Thomas',
      email: 'henry@hotmail.com',
      phoneNumber: '2109876543',
      company: 'Innovate Solutions',
      service: 'Social Media Marketing',
      budget: '$10,000 - $20,000',
   },
   {
      name: 'Ivy Taylor',
      email: 'ivy@outlook.com',
      phoneNumber: '1098765432',
      company: 'Web Experts',
      service: 'Front-end Development',
      budget: '$15,000 - $25,000',
   },
   {
      name: 'Jack Robinson',
      email: 'jack@mail.com',
      phoneNumber: '9876543210',
      company: 'Digital Creations',
      service: 'Back-end Development',
      budget: '$18,000 - $28,000',
   },
   {
      name: 'Karen White',
      email: 'karen@gmail.com',
      phoneNumber: '8765432109',
      company: 'Innovate Designers',
      service: 'App Maintenance',
      budget: '$10,000 - $15,000',
   },
   {
      name: 'Leo Brown',
      email: 'leo@yahoo.com',
      phoneNumber: '7654321098',
      company: 'Tech Wizards',
      service: 'Database Management',
      budget: '$8,000 - $14,000',
   },
   {
      name: 'Mia Davis',
      email: 'mia@hotmail.com',
      phoneNumber: '6543210987',
      company: 'Web Innovations',
      service: 'Digital Marketing',
      budget: '$12,000 - $20,000',
   },
   {
      name: 'Nathan Wilson',
      email: 'nathan@outlook.com',
      phoneNumber: '5432109876',
      company: 'Innovate Solutions',
      service: 'Cybersecurity',
      budget: '$20,000 - $30,000',
   },
   {
      name: 'Olivia Smith',
      email: 'olivia@mail.com',
      phoneNumber: '4321098765',
      company: 'Tech Gurus',
      service: 'Web Development',
      budget: '$25,000 - $35,000',
   },
   {
      name: 'Paula Brown',
      email: 'paula@gmail.com',
      phoneNumber: '3210987654',
      company: 'Digital Creations',
      service: 'Mobile App Design',
      budget: '$7,000 - $15,000',
   },
   {
      name: 'Quincy Thomas',
      email: 'quincy@yahoo.com',
      phoneNumber: '2109876543',
      company: 'Innovate Tech',
      service: 'UI/UX Testing',
      budget: '$10,000 - $20,000',
   },
   {
      name: 'Rachel Taylor',
      email: 'rachel@outlook.com',
      phoneNumber: '1098765432',
      company: 'Web Experts',
      service: 'Content Creation',
      budget: '$15,000 - $25,000',
   },
   {
      name: 'Sam Robinson',
      email: 'sam@mail.com',
      phoneNumber: '9876543210',
      company: 'Tech Innovations',
      service: 'SEO Services',
      budget: '$18,000 - $28,000',
   },
   {
      name: 'Tina White',
      email: 'tina@gmail.com',
      phoneNumber: '8765432109',
      company: 'Global Ventures',
      service: 'E-commerce Solutions',
      budget: '$10,000 - $15,000',
   },
];
